# 개발자
author:
  name  : "Jowrney Kim"
  mail  : "jowrney@jowrney.com"
  url   : http://luplin.com

# 웹사이트 정보
title   : "RealGrid2"
description: ""
tagline : ''
version : 1.0.0
gitlab  :
  repo: "https://gitlab.com/Jowrney/rg2-luplin-com.git"

# 소스 디렉토리 정의
source          : .
destination     : _site
plugins_dir     : _plugins
layouts_dir     : _layouts
includes_dir    : _includes
#collections_dir : _posts
#collections     :
#  posts:
#    output:   true

# 읽기 핸들링
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/","CNAME",".idea"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# 필터링
show_drafts   : null
limit_posts   : 0
future        : false
unpublished   : false

# 플러그인
whitelist     : []
plugins       : [jekyll-polyglot, jekyll-paginate, jekyll-feed]

# 코딩규칙
markdown          : kramdown
highlighter       : rouge
lsi               : false
excerpt_separator : "\n\n"
incremental       : false

# 서버
detach            : false
port              : 2020
host              : 127.0.0.1
#host              : 192.168.200.117
baseurl           : "" # does not include hostname
url               : "http://hopeden.com"
show_dir_listing  : false

# 아웃풋
permalink       : pretty
paginate        : 5
paginate_path   : "/blog/page:num/"
timezone        : null
quiet           : false
verbose         : false
defaults        : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

sass:
  #style: compressed
  sass_dir: _sass

# 마크다운 프로세서
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids      : true
  entity_output : as_char
  toc_levels    : 1..6
  smart_quotes  : lsquo,rsquo,ldquo,rdquo
  input         : GFM
  hard_wrap     : false
  footnote_nr   : 1
  show_warnings : false

#자산
assets:
  sources:
    - assets