name: Deploy sample site

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/sample.yml'
    - 'sample/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Build Jekyll
      working-directory: sample
      run: |
        gem install bundler
        gem install jekyll
        bundle install
    
    - name: Build Site
      env:
        JEKYLL_ENV: production
      working-directory: sample
      run: bundle exec jekyll build

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-2'
        SOURCE_DIR: 'sample/_site'

    - name: Slack Notification Success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#238636'
        SLACK_TITLE: '✅ 배포 성공 알림'
        SLACK_MESSAGE: '<https://sample.realgrid.com|그리드샘플사이트> 서비스가 정상적으로 배포되었습니다.'
        MSG_MINIMAL: true
        SLACK_USERNAME: github_action
        # 웹 훅 경로에 채널 정보가 포함되어 채널을 조정 할 수 없다.
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: '<https://www.wooritech.com|wooritech>'

    - name: Slack Notification Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#ff0000'
        SLACK_TITLE: '❌ 배포 실패 알림'
        SLACK_MESSAGE: '<https://sample.realgrid.com|그리드샘플사이트> 서비스 배포중 문제가 생겼습니다.'
        SLACK_USERNAME: github_action
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: '<https://www.wooritech.com|wooritech>'
