name: Deploy sample site

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/sample.yml'
    - 'sample/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Build Jekyll
      working-directory: sample
      run: |
        gem install bundler
        gem install jekyll
        bundle install
    
    - name: Build Site
      env:
        JEKYLL_ENV: production
      working-directory: sample
      run: bundle exec jekyll build

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-2'
        SOURCE_DIR: 'sample/_site'
